# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/diptorch',
                'doc_host': 'https://eigenvivek.github.io',
                'git_url': 'https://github.com/eigenvivek/diptorch',
                'lib_path': 'diptorch'},
  'syms': { 'diptorch.filters': { 'diptorch.filters._conv': ('filters.html#_conv', 'diptorch/filters.py'),
                                  'diptorch.filters._gaussian_kernel_1d': ('filters.html#_gaussian_kernel_1d', 'diptorch/filters.py'),
                                  'diptorch.filters._hessian_2d': ('filters.html#_hessian_2d', 'diptorch/filters.py'),
                                  'diptorch.filters._hessian_3d': ('filters.html#_hessian_3d', 'diptorch/filters.py'),
                                  'diptorch.filters.gaussian_filter': ('filters.html#gaussian_filter', 'diptorch/filters.py'),
                                  'diptorch.filters.hessian': ('filters.html#hessian', 'diptorch/filters.py')},
            'diptorch.linalg': { 'diptorch.linalg._is_hermitian': ('linalg.html#_is_hermitian', 'diptorch/linalg.py'),
                                 'diptorch.linalg._is_square': ('linalg.html#_is_square', 'diptorch/linalg.py'),
                                 'diptorch.linalg.eigvalsh': ('linalg.html#eigvalsh', 'diptorch/linalg.py'),
                                 'diptorch.linalg.eigvalsh2': ('linalg.html#eigvalsh2', 'diptorch/linalg.py'),
                                 'diptorch.linalg.eigvalsh3': ('linalg.html#eigvalsh3', 'diptorch/linalg.py')},
            'diptorch.utils': {'diptorch.utils.astronaut': ('utils.html#astronaut', 'diptorch/utils.py')}}}
