# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/diptorch',
                'doc_host': 'https://eigenvivek.github.io',
                'git_url': 'https://github.com/eigenvivek/diptorch',
                'lib_path': 'diptorch'},
  'syms': {'diptorch.filter': {'diptorch.filter.foo': ('filter.html#foo', 'diptorch/filter.py')}}}
