# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/01_linalg.ipynb.

# %% auto 0
__all__ = ['eigvalsh2']

# %% ../notebooks/01_linalg.ipynb 3
import torch

# %% ../notebooks/01_linalg.ipynb 5
def eigvalsh2(ii, ij, jj):
    tr = ii + jj
    det = ii * jj - ii.square()

    disc = (tr.square() - 4 * det).sqrt()
    disc = torch.concat([-disc, disc], dim=-1)

    eigvals = (tr + disc) / 2
    return eigvals
